#!/bin/sh
#
# Writes GADApplicationIdentifier into the built Info.plist.
#
# Why this exists: the Google Mobile Ads SDK reads its application identifier
# from Info.plist and throws GADInvalidInitializationException — a hard crash on
# launch — when the key is missing. Kudao has no Info.plist of its own: the file
# is generated by Xcode from the INFOPLIST_KEY_* build settings, and that
# mechanism only covers keys Xcode knows about. GADApplicationIdentifier is not
# one of them, so the setting was silently dropped and every launch crashed.
#
# This phase runs after the Info.plist is generated and before code signing, so
# the key lands in the bundle without a hand-written Info.plist and without
# losing any of the generated keys (usage descriptions, orientations, scene
# manifest).
#
# The value comes from the project's own setting, EXPO_PUBLIC_ADMOB_IOS_APP_ID,
# read out of the generated EnvConfig.swift so it can never drift from the
# identifier the app requests ads with. Without it the build falls back to
# Google's public demo application, which always fills, earns nothing and keeps
# an unconfigured build from sending invalid traffic to a real AdMob account.

PLIST="${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
ENV_CONFIG="${SRCROOT}/Kudao/Utilities/EnvConfig.swift"
DEMO_APP_ID="ca-app-pub-3940256099942544~1458002511"
GOOGLE_SKADNETWORK="cstr6suwn9.skadnetwork"

if [ ! -f "$PLIST" ]; then
  echo "warning: Info.plist not found at $PLIST, AdMob identifier not injected"
  exit 0
fi

APP_ID=""
if [ -f "$ENV_CONFIG" ]; then
  APP_ID=$(LC_ALL=C sed -n \
    's/^[[:space:]]*static let EXPO_PUBLIC_ADMOB_IOS_APP_ID[[:space:]]*=[[:space:]]*"\(.*\)"[[:space:]]*$/\1/p' \
    "$ENV_CONFIG" | head -1)
fi

if [ -z "$APP_ID" ]; then
  APP_ID="$DEMO_APP_ID"
  echo "note: EXPO_PUBLIC_ADMOB_IOS_APP_ID is empty, using Google's demo application id"
fi

PB=/usr/libexec/PlistBuddy

"$PB" -c "Set :GADApplicationIdentifier $APP_ID" "$PLIST" 2>/dev/null \
  || "$PB" -c "Add :GADApplicationIdentifier string $APP_ID" "$PLIST" \
  || { echo "error: could not write GADApplicationIdentifier into $PLIST"; exit 1; }

# Attribution for the ads Kudao serves. Only Google's own identifier is listed:
# the SDK needs it, and the partner list belongs to whoever is actually paying
# for installs.
if ! "$PB" -c "Print :SKAdNetworkItems" "$PLIST" >/dev/null 2>&1; then
  "$PB" -c "Add :SKAdNetworkItems array" "$PLIST" >/dev/null 2>&1
  "$PB" -c "Add :SKAdNetworkItems:0 dict" "$PLIST" >/dev/null 2>&1
  "$PB" -c "Add :SKAdNetworkItems:0:SKAdNetworkIdentifier string $GOOGLE_SKADNETWORK" "$PLIST" >/dev/null 2>&1
fi

echo "note: GADApplicationIdentifier set to $APP_ID"
exit 0
