//
//  MessageTabView.swift
//  Kudao
//

import SwiftUI
import SwiftData
import UIKit

/// Ready-to-send birthday message: generated by the AI, editable, and scheduled by the user.
struct MessageTabView: View {
    let profile: BirthdayProfile
    @Bindable var composer: GreetingComposer

    @Environment(AppSettings.self) private var settings
    @Environment(NotificationService.self) private var notifications
    @Environment(\.modelContext) private var modelContext
    @Environment(\.openURL) private var openURL
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    @State private var didCopy: Bool = false
    @State private var sharedText: SharedGreeting?
    @State private var openFailed: Bool = false
    @State private var isConfirmingSent: Bool = false
    @State private var phoneDraft: String = ""
    @State private var emailDraft: String = ""
    @FocusState private var isEditingText: Bool
    @FocusState private var focusedContact: ContactField?

    private enum ContactField: Hashable {
        case phone
        case email
    }

    private var strings: Strings { settings.strings }

    /// The stored record, when one already exists. Never created just by looking at the tab.
    private var message: BirthdayMessage? {
        guard let stored = profile.birthdayMessage, !stored.isDeleted else { return nil }
        return stored
    }

    private var phone: String {
        profile.contactPhone.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private var email: String {
        profile.contactEmail.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// Only the profile owner edits the saved contact details.
    private var canEditContact: Bool { profile.isOwnedByMe }

    var body: some View {
        VStack(spacing: 16) {
            toneRow

            if let error = composer.errorMessage {
                errorBanner(error)
            }

            if composer.isGenerating && !(message?.hasText ?? false) {
                generatingPanel
            } else if let message, message.hasText {
                messageCard(message)
                autoRefreshCard(message)
                scheduleCard(message)
                contactCard
                sendRow(message)
            } else {
                emptyPanel
            }
        }
        .onAppear {
            phoneDraft = profile.contactPhone
            emailDraft = profile.contactEmail
            composer.adoptTone(from: profile)
        }
        .onChange(of: isEditingText) { _, editing in
            // Committing the text refreshes the notification preview.
            guard !editing, let message else { return }
            message.updatedAt = Date()
            composer.save(modelContext)
        }
        .onChange(of: focusedContact) { _, focused in
            guard focused == nil else { return }
            commitContacts()
        }
        .onChange(of: reminderSignature) { _, _ in
            rescheduleReminders()
        }
        .sheet(item: $sharedText) { shared in
            ShareSheet(text: shared.text)
        }
        .alert(strings.messageOpenFailedTitle, isPresented: $openFailed) {
            Button(strings.doneAction, role: .cancel) {}
        } message: {
            Text(strings.messageOpenFailedMessage)
        }
        .alert(strings.messageSentConfirmTitle, isPresented: $isConfirmingSent) {
            Button(strings.messageMarkSentAction) { setSent(true) }
            Button(strings.messageNotYetAction, role: .cancel) {}
        } message: {
            Text(strings.messageSentConfirmMessage)
        }
    }

    /// Changes that must be mirrored into the scheduled send reminder.
    private var reminderSignature: String {
        guard let message else { return "none" }
        return [
            message.isScheduleEnabled ? "1" : "0",
            message.isSent ? "1" : "0",
            String(Int(message.scheduledAt.timeIntervalSince1970)),
            String(Int(message.updatedAt.timeIntervalSince1970)),
        ].joined(separator: "|")
    }

    // MARK: - Tone

    private var toneRow: some View {
        VStack(alignment: .leading, spacing: 9) {
            HStack(spacing: 6) {
                Text(strings.messageToneLabel.uppercased())
                    .font(.system(.caption2, design: .rounded, weight: .bold))
                    .tracking(1)
                    .foregroundStyle(.secondary)

                Spacer(minLength: 0)

                KudaoChip(
                    title: profile.ageBracket.title(strings),
                    systemImage: profile.ageBracket.symbolName,
                    tint: Palette.violet
                )
            }

            HStack(spacing: 8) {
                ForEach(GreetingTone.allCases) { tone in
                    let isSelected = tone == composer.tone
                    Button {
                        withAnimation(reduceMotion ? nil : .smooth(duration: 0.25)) {
                            composer.tone = tone
                        }
                    } label: {
                        HStack(spacing: 5) {
                            Image(systemName: tone.symbolName)
                                .font(.system(size: 10, weight: .bold))
                            Text(tone.title(strings))
                                .font(.system(.footnote, design: .rounded, weight: .bold))
                                .lineLimit(1)
                                .minimumScaleFactor(0.8)
                        }
                        .foregroundStyle(isSelected ? .white : Color.secondary)
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 9)
                        .background(
                            Capsule().fill(
                                isSelected
                                    ? AnyShapeStyle(Palette.warmGradient)
                                    : AnyShapeStyle(Palette.surface)
                            )
                        )
                        .overlay(
                            Capsule().strokeBorder(
                                isSelected ? .clear : Palette.hairline,
                                lineWidth: 1
                            )
                        )
                    }
                    .buttonStyle(PressableCardStyle())
                }
            }
        }
    }

    // MARK: - Message

    private func messageCard(_ message: BirthdayMessage) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 8) {
                Image(systemName: "paperplane.fill")
                    .font(.system(size: 12, weight: .bold))
                    .foregroundStyle(Palette.coral)
                Text(strings.messageSectionTitle)
                    .font(.system(.caption, design: .rounded, weight: .bold))
                    .textCase(.uppercase)
                    .foregroundStyle(.secondary)

                Spacer(minLength: 0)

                if composer.isGenerating {
                    ProgressView().controlSize(.mini).tint(Palette.coral)
                } else if message.isSent {
                    KudaoChip(
                        title: strings.messageSentBadge,
                        systemImage: "checkmark.circle.fill",
                        tint: Palette.teal
                    )
                }
            }

            ZStack(alignment: .topLeading) {
                TextEditor(text: textBinding(message))
                    .font(.system(.body, design: .rounded, weight: .medium))
                    .scrollContentBackground(.hidden)
                    .frame(minHeight: 132)
                    .focused($isEditingText)
                    .tint(Palette.coral)

                if !message.hasText {
                    Text(strings.messagePlaceholder)
                        .font(.system(.body, design: .rounded, weight: .medium))
                        .foregroundStyle(.tertiary)
                        .padding(.top, 8)
                        .padding(.leading, 5)
                        .allowsHitTesting(false)
                }
            }
            .padding(.horizontal, 4)
            .background(
                RoundedRectangle(cornerRadius: 16, style: .continuous)
                    .fill(Palette.surfaceRaised.opacity(0.6))
            )

            HStack(spacing: 7) {
                Image(systemName: "sparkles")
                    .font(.system(size: 9, weight: .bold))
                Text(isEditingText ? strings.messageEditorHint : strings.messageBasedOnNote)
                    .font(.system(.caption2, design: .rounded, weight: .medium))
                    .lineLimit(2)
                Spacer(minLength: 0)

                if isEditingText {
                    Button(strings.doneAction) {
                        isEditingText = false
                    }
                    .font(.system(.caption, design: .rounded, weight: .bold))
                    .foregroundStyle(Palette.coral)
                } else {
                    Button {
                        composer.generate(for: profile, language: settings.language, context: modelContext)
                    } label: {
                        HStack(spacing: 4) {
                            Image(systemName: "arrow.triangle.2.circlepath")
                                .font(.system(size: 10, weight: .heavy))
                            Text(strings.messageRegenerateAction)
                                .font(.system(.caption, design: .rounded, weight: .bold))
                        }
                        .foregroundStyle(Palette.coral)
                        .padding(.horizontal, 10)
                        .padding(.vertical, 6)
                        .background(Capsule().fill(Palette.coral.opacity(0.13)))
                    }
                    .buttonStyle(PressableCardStyle())
                    .disabled(composer.isGenerating)
                }
            }
            .foregroundStyle(.tertiary)
        }
        .padding(16)
        .background(
            RoundedRectangle(cornerRadius: 24, style: .continuous)
                .fill(Palette.surface)
        )
        .overlay(
            RoundedRectangle(cornerRadius: 24, style: .continuous)
                .strokeBorder(Palette.hairline, lineWidth: 1)
        )
        .shadow(color: .black.opacity(0.05), radius: 12, y: 6)
    }

    /// Writes straight into the stored record so edits survive tab switches.
    ///
    /// A manual edit also pauses the automatic rewrites, so what the user typed
    /// is never replaced by a new diary-driven generation.
    private func textBinding(_ message: BirthdayMessage) -> Binding<String> {
        Binding(
            get: { message.text },
            set: { newValue in
                guard newValue != message.text else { return }
                message.text = newValue
                message.markUserEdited()
            }
        )
    }

    // MARK: - Automatic refresh

    /// Keeps the draft in step with the diary, unless the user took over the text.
    private func autoRefreshCard(_ message: BirthdayMessage) -> some View {
        VStack(alignment: .leading, spacing: 10) {
            Toggle(isOn: autoRefreshBinding(message)) {
                VStack(alignment: .leading, spacing: 2) {
                    Text(strings.messageAutoRefreshToggle)
                        .font(.system(.subheadline, design: .rounded, weight: .semibold))
                    Text(strings.messageAutoRefreshCaption)
                        .font(.system(.caption2, design: .rounded))
                        .foregroundStyle(.secondary)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
            .tint(Palette.violet)

            if message.isUserEdited, message.isAutoRefreshEnabled {
                Divider().overlay(Palette.hairline)

                HStack(alignment: .top, spacing: 9) {
                    Image(systemName: "hand.raised.fill")
                        .font(.system(size: 11, weight: .bold))
                        .foregroundStyle(Palette.amber)
                        .padding(.top, 2)

                    Text(strings.messageAutoRefreshPausedLabel)
                        .font(.system(.caption, design: .rounded, weight: .medium))
                        .foregroundStyle(.secondary)
                        .fixedSize(horizontal: false, vertical: true)

                    Spacer(minLength: 0)

                    Button(strings.messageAutoRefreshResumeAction) {
                        resumeAutoRefresh(message)
                    }
                    .font(.system(.caption, design: .rounded, weight: .bold))
                    .buttonStyle(.plain)
                    .foregroundStyle(Palette.coral)
                    .disabled(composer.isGenerating)
                }
            } else if let refreshedAt = message.autoRefreshedAt {
                Divider().overlay(Palette.hairline)

                HStack(spacing: 7) {
                    Image(systemName: "sparkles")
                        .font(.system(size: 10, weight: .bold))
                        .foregroundStyle(Palette.violet)
                    Text(
                        String(
                            format: strings.messageAutoRefreshedFormat,
                            settings.noteTimestamp(refreshedAt)
                        )
                    )
                    .font(.system(.caption2, design: .rounded, weight: .medium))
                    .foregroundStyle(.secondary)
                    Spacer(minLength: 0)
                }
            }
        }
        .padding(16)
        .background(
            RoundedRectangle(cornerRadius: 24, style: .continuous)
                .fill(Palette.surface)
        )
        .overlay(
            RoundedRectangle(cornerRadius: 24, style: .continuous)
                .strokeBorder(Palette.hairline, lineWidth: 1)
        )
    }

    private func autoRefreshBinding(_ message: BirthdayMessage) -> Binding<Bool> {
        Binding(
            get: { message.isAutoRefreshEnabled },
            set: { newValue in
                message.isAutoRefreshEnabled = newValue
                message.updatedAt = Date()
                composer.save(modelContext)
            }
        )
    }

    /// Gives the draft back to the diary and rewrites it right away.
    private func resumeAutoRefresh(_ message: BirthdayMessage) {
        message.resumeAutoRefresh()
        composer.save(modelContext)

        Task {
            let changed = await composer.regenerate(
                for: profile,
                language: settings.language,
                context: modelContext
            )
            if changed { rescheduleReminders() }
        }
    }

    // MARK: - Schedule

    private func scheduleCard(_ message: BirthdayMessage) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 8) {
                Image(systemName: "clock.badge.checkmark.fill")
                    .font(.system(size: 12, weight: .bold))
                    .foregroundStyle(Palette.amber)
                Text(strings.messageScheduleTitle)
                    .font(.system(.caption, design: .rounded, weight: .bold))
                    .textCase(.uppercase)
                    .foregroundStyle(.secondary)
                Spacer(minLength: 0)
            }

            Toggle(isOn: scheduleBinding(message)) {
                Text(strings.messageScheduleToggle)
                    .font(.system(.subheadline, design: .rounded, weight: .semibold))
            }
            .tint(Palette.amber)

            if message.isScheduleEnabled {
                Divider().overlay(Palette.hairline)

                DatePicker(
                    strings.messageSendDateLabel,
                    selection: dateBinding(message),
                    in: Date()...,
                    displayedComponents: [.date, .hourAndMinute]
                )
                .font(.system(.subheadline, design: .rounded, weight: .semibold))
                .datePickerStyle(.compact)
                .tint(Palette.coral)

                HStack(spacing: 7) {
                    Image(systemName: message.reminderFireDate == nil ? "bell.slash.fill" : "bell.fill")
                        .font(.system(size: 10, weight: .bold))
                    Text(scheduleStatus(message))
                        .font(.system(.caption2, design: .rounded, weight: .medium))
                        .fixedSize(horizontal: false, vertical: true)
                    Spacer(minLength: 0)
                }
                .foregroundStyle(message.reminderFireDate == nil ? Palette.amber : .secondary)
            }

            Divider().overlay(Palette.hairline)

            Button {
                setSent(!message.isSent)
            } label: {
                HStack(spacing: 8) {
                    Image(systemName: message.isSent ? "arrow.uturn.backward" : "checkmark.circle")
                        .font(.system(size: 12, weight: .bold))
                    Text(message.isSent ? strings.messageMarkUnsentAction : strings.messageMarkSentShortAction)
                        .font(.system(.subheadline, design: .rounded, weight: .bold))
                    Spacer(minLength: 0)
                    if message.isSent, let sentAt = message.sentAt {
                        Text(settings.noteTimestamp(sentAt))
                            .font(.system(.caption2, design: .rounded))
                            .foregroundStyle(.secondary)
                    }
                }
                .foregroundStyle(message.isSent ? Color.secondary : Palette.teal)
                .contentShape(Rectangle())
            }
            .buttonStyle(PressableCardStyle())
        }
        .padding(16)
        .background(
            RoundedRectangle(cornerRadius: 24, style: .continuous)
                .fill(Palette.surface)
        )
        .overlay(
            RoundedRectangle(cornerRadius: 24, style: .continuous)
                .strokeBorder(Palette.hairline, lineWidth: 1)
        )
    }

    private func scheduleStatus(_ message: BirthdayMessage) -> String {
        if message.isSent { return strings.messageAlreadySentLabel }
        guard let fire = message.reminderFireDate else { return strings.messagePastDateLabel }
        return String(format: strings.messageScheduleReadyFormat, scheduleLabel(fire))
    }

    /// "3 giugno, 09:00" in the selected language.
    private func scheduleLabel(_ date: Date) -> String {
        let time = date.formatted(
            Date.FormatStyle(locale: settings.locale)
                .hour(.defaultDigits(amPM: .abbreviated))
                .minute(.twoDigits)
        )
        return "\(settings.dayMonth(date)), \(time)"
    }

    private func scheduleBinding(_ message: BirthdayMessage) -> Binding<Bool> {
        Binding(
            get: { message.isScheduleEnabled },
            set: { newValue in
                message.isScheduleEnabled = newValue
                message.updatedAt = Date()
                composer.save(modelContext)
            }
        )
    }

    private func dateBinding(_ message: BirthdayMessage) -> Binding<Date> {
        Binding(
            get: { max(message.scheduledAt, Date()) },
            set: { newValue in
                message.scheduledAt = newValue
                message.updatedAt = Date()
                composer.save(modelContext)
            }
        )
    }

    // MARK: - Contact

    /// Where the greeting should go: saved on the profile so it is remembered next year.
    private var contactCard: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 8) {
                Image(systemName: "person.crop.circle.badge.checkmark")
                    .font(.system(size: 12, weight: .bold))
                    .foregroundStyle(Palette.teal)
                Text(strings.messageContactTitle)
                    .font(.system(.caption, design: .rounded, weight: .bold))
                    .textCase(.uppercase)
                    .foregroundStyle(.secondary)
                Spacer(minLength: 0)
            }

            if canEditContact {
                HStack(spacing: 11) {
                    Image(systemName: "phone.fill")
                        .font(.system(size: 13, weight: .bold))
                        .foregroundStyle(Palette.teal)
                        .frame(width: 22)
                    TextField(strings.phonePlaceholder, text: $phoneDraft)
                        .font(.system(.body, design: .rounded, weight: .medium))
                        .textContentType(.telephoneNumber)
                        .keyboardType(.phonePad)
                        .focused($focusedContact, equals: .phone)
                }

                Divider().overlay(Palette.hairline)

                HStack(spacing: 11) {
                    Image(systemName: "envelope.fill")
                        .font(.system(size: 13, weight: .bold))
                        .foregroundStyle(Palette.amber)
                        .frame(width: 22)
                    TextField(strings.emailPlaceholder, text: $emailDraft)
                        .font(.system(.body, design: .rounded, weight: .medium))
                        .textContentType(.emailAddress)
                        .keyboardType(.emailAddress)
                        .textInputAutocapitalization(.never)
                        .autocorrectionDisabled()
                        .focused($focusedContact, equals: .email)
                }

                Text(strings.messageContactCaption)
                    .font(.system(.caption2, design: .rounded))
                    .foregroundStyle(.tertiary)
                    .fixedSize(horizontal: false, vertical: true)
            } else {
                Text(phone.isEmpty && email.isEmpty ? strings.messageNoContactLabel : [phone, email].filter { !$0.isEmpty }.joined(separator: " \u{00B7} "))
                    .font(.system(.subheadline, design: .rounded, weight: .medium))
                    .foregroundStyle(phone.isEmpty && email.isEmpty ? .secondary : .primary)
            }
        }
        .padding(16)
        .background(
            RoundedRectangle(cornerRadius: 24, style: .continuous)
                .fill(Palette.surface)
        )
        .overlay(
            RoundedRectangle(cornerRadius: 24, style: .continuous)
                .strokeBorder(Palette.hairline, lineWidth: 1)
        )
    }

    private func commitContacts() {
        guard canEditContact else { return }
        let newPhone = phoneDraft.trimmingCharacters(in: .whitespacesAndNewlines)
        let newEmail = emailDraft.trimmingCharacters(in: .whitespacesAndNewlines)
        guard newPhone != profile.contactPhone || newEmail != profile.contactEmail else { return }
        profile.contactPhone = newPhone
        profile.contactEmail = newEmail
        composer.save(modelContext)
    }

    // MARK: - Sending

    private func sendRow(_ message: BirthdayMessage) -> some View {
        let text = message.trimmedText

        return VStack(spacing: 10) {
            HStack(spacing: 10) {
                actionButton(
                    title: strings.messageWhatsAppAction,
                    systemImage: "bubble.left.and.text.bubble.right.fill",
                    tint: Palette.teal
                ) {
                    openWhatsApp(text)
                }

                actionButton(
                    title: strings.messageMessagesAction,
                    systemImage: "message.fill",
                    tint: Palette.coral
                ) {
                    openSMS(text)
                }
            }

            HStack(spacing: 10) {
                actionButton(
                    title: didCopy ? strings.messageCopiedLabel : strings.messageCopyAction,
                    systemImage: didCopy ? "checkmark" : "doc.on.doc.fill",
                    tint: Palette.violet
                ) {
                    copy(text)
                }

                if email.isEmpty {
                    actionButton(
                        title: strings.messageShareAction,
                        systemImage: "square.and.arrow.up",
                        tint: Palette.berry
                    ) {
                        sharedText = SharedGreeting(text: text)
                    }
                } else {
                    actionButton(
                        title: strings.messageEmailAction,
                        systemImage: "envelope.fill",
                        tint: Palette.amber
                    ) {
                        openMail(text)
                    }
                }
            }

            if phone.isEmpty {
                HStack(spacing: 7) {
                    Image(systemName: "info.circle.fill")
                        .font(.system(size: 10, weight: .bold))
                    Text(strings.messageNeedsPhoneHint)
                        .font(.system(.caption2, design: .rounded, weight: .medium))
                        .fixedSize(horizontal: false, vertical: true)
                    Spacer(minLength: 0)
                }
                .foregroundStyle(.tertiary)
            }
        }
        .sensoryFeedback(.success, trigger: didCopy)
    }

    private func actionButton(
        title: String,
        systemImage: String,
        tint: Color,
        action: @escaping () -> Void
    ) -> some View {
        Button(action: action) {
            HStack(spacing: 7) {
                Image(systemName: systemImage)
                    .font(.system(size: 13, weight: .bold))
                    .contentTransition(.symbolEffect(.replace))
                Text(title)
                    .font(.system(.subheadline, design: .rounded, weight: .bold))
                    .lineLimit(1)
                    .minimumScaleFactor(0.8)
            }
            .foregroundStyle(tint)
            .frame(maxWidth: .infinity)
            .padding(.vertical, 13)
            .background(
                RoundedRectangle(cornerRadius: 18, style: .continuous)
                    .fill(tint.opacity(0.12))
            )
            .overlay(
                RoundedRectangle(cornerRadius: 18, style: .continuous)
                    .strokeBorder(tint.opacity(0.28), lineWidth: 1)
            )
        }
        .buttonStyle(PressableCardStyle())
    }

    private func copy(_ text: String) {
        UIPasteboard.general.string = text
        withAnimation(.smooth(duration: 0.2)) { didCopy = true }
        Task {
            try? await Task.sleep(for: .seconds(2))
            withAnimation(.smooth(duration: 0.2)) { didCopy = false }
        }
    }

    private var digits: String {
        phone.filter(\.isNumber)
    }

    /// WhatsApp opens on the saved number when there is one, otherwise on the chat picker.
    private func openWhatsApp(_ text: String) {
        var components = URLComponents()
        components.scheme = "whatsapp"
        components.host = "send"
        var items = [URLQueryItem(name: "text", value: text)]
        if !digits.isEmpty {
            items.insert(URLQueryItem(name: "phone", value: digits), at: 0)
        }
        components.queryItems = items
        guard let url = components.url else { return }
        openExternal(url, fallbackText: text)
    }

    /// Messages with the greeting prefilled; the saved number is optional.
    private func openSMS(_ text: String) {
        let encoded = text.addingPercentEncoding(withAllowedCharacters: .alphanumerics) ?? ""
        let recipient = phone.filter { $0.isNumber || $0 == "+" }
        let raw = recipient.isEmpty ? "sms:&body=\(encoded)" : "sms:\(recipient)&body=\(encoded)"
        guard let url = URL(string: raw) else { return }
        openExternal(url, fallbackText: text)
    }

    /// Opens Mail with subject and greeting prefilled for the saved address.
    private func openMail(_ text: String) {
        var components = URLComponents()
        components.scheme = "mailto"
        components.path = email
        components.queryItems = [
            URLQueryItem(name: "subject", value: String(format: strings.messageEmailSubjectFormat, profile.name)),
            URLQueryItem(name: "body", value: text)
        ]
        guard let url = components.url else { return }
        openExternal(url, fallbackText: text)
    }

    /// Hands the URL to iOS; if no app can open it the text is copied instead.
    private func openExternal(_ url: URL, fallbackText: String) {
        Task {
            let opened = await UIApplication.shared.open(url)
            if opened {
                try? await Task.sleep(for: .seconds(1))
                isConfirmingSent = true
            } else {
                UIPasteboard.general.string = fallbackText
                openFailed = true
            }
        }
    }

    private func setSent(_ sent: Bool) {
        guard let message else { return }
        message.markSent(sent)
        composer.save(modelContext)
    }

    // MARK: - Reminders

    /// Keeps the local "time to send your wishes" notification in sync with the record.
    private func rescheduleReminders() {
        let strings = self.strings
        let privacy = ReminderPrivacy(hidesSurprisePreviews: settings.hidesSurpriseNotificationPreviews)
        Task {
            await notifications.sync(profile: profile, strings: strings, privacy: privacy)
        }
    }

    // MARK: - States

    private var generatingPanel: some View {
        VStack(spacing: 14) {
            ProgressView().tint(Palette.coral)
            Text(strings.messageGeneratingTitle)
                .font(.system(.headline, design: .rounded, weight: .bold))
            Text(strings.messageGeneratingMessage)
                .font(.system(.subheadline, design: .rounded))
                .foregroundStyle(.secondary)
                .multilineTextAlignment(.center)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 34)
        .padding(.horizontal, 24)
        .background(
            RoundedRectangle(cornerRadius: 26, style: .continuous)
                .fill(Palette.surface)
        )
        .overlay(
            RoundedRectangle(cornerRadius: 26, style: .continuous)
                .strokeBorder(Palette.hairline, lineWidth: 1)
        )
    }

    private var emptyPanel: some View {
        VStack(spacing: 14) {
            PlaceholderPanel(
                icon: "paperplane",
                title: strings.messageEmptyTitle,
                message: strings.messageEmptyMessage
            )

            Button {
                composer.generate(for: profile, language: settings.language, context: modelContext)
            } label: {
                Label(strings.messageGenerateAction, systemImage: "sparkles")
                    .font(.system(.headline, design: .rounded, weight: .bold))
                    .foregroundStyle(.white)
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 15)
                    .background(Capsule().fill(Palette.warmGradient))
                    .shadow(color: Palette.coral.opacity(0.3), radius: 12, y: 6)
            }
            .buttonStyle(PressableCardStyle())

            Button {
                composer.record(for: profile, context: modelContext)
                isEditingText = true
            } label: {
                Text(strings.messageWriteMyselfAction)
                    .font(.system(.subheadline, design: .rounded, weight: .bold))
                    .foregroundStyle(Palette.coral)
            }
            .buttonStyle(PressableCardStyle())
        }
    }

    private func errorBanner(_ text: String) -> some View {
        HStack(spacing: 10) {
            Image(systemName: "exclamationmark.triangle.fill")
                .font(.system(size: 13, weight: .bold))
                .foregroundStyle(Palette.amber)
            Text(text)
                .font(.system(.footnote, design: .rounded, weight: .medium))
                .fixedSize(horizontal: false, vertical: true)
            Spacer(minLength: 0)
            Button {
                composer.clearError()
            } label: {
                Image(systemName: "xmark")
                    .font(.system(size: 11, weight: .bold))
                    .foregroundStyle(.secondary)
            }
        }
        .padding(14)
        .background(
            RoundedRectangle(cornerRadius: 20, style: .continuous)
                .fill(Palette.amber.opacity(0.12))
        )
        .overlay(
            RoundedRectangle(cornerRadius: 20, style: .continuous)
                .strokeBorder(Palette.amber.opacity(0.3), lineWidth: 1)
        )
    }
}

/// Wrapper so the share sheet can be driven by an optional item.
struct SharedGreeting: Identifiable {
    let id: UUID = UUID()
    let text: String
}
